#define _POSIX_VERSION 200809L

#define _POSIX_ASYNCHRONOUS_IO 200809L
#define _POSIX_BARRIERS 200809L
#define _POSIX_CLOCK_SELECTION 200809L
#define _POSIX_MAPPED_FILES 200809L
#define _POSIX_MEMORY_PROTECTION 200809L
#define _POSIX_READER_WRITER_LOCKS 200809L
#define _POSIX_REALTIME_SIGNALS 200809L
#define _POSIX_SEMAPHORES 200809L
#define _POSIX_SPIN_LOCKS 200809L
#define _POSIX_THREAD_SAFE_FUNCTIONS 200809L
#define _POSIX_THREADS 200809L
#define _POSIX_TIMEOUTS 200809L
#define _POSIX_TIMERS 200809L

/* Value greater than `0'. */
#define _POSIX_JOB_CONTROL 1
#define _POSIX_SAVED_IDS 1

/* Value other than `-1'. */
#define _POSIX_VDISABLE 0


/* If any of the symbolic constants `_POSIX_TRACE_EVENT_FILTER',
 * `_POSIX_TRACE_LOG', or `POSIX_TRACE_INHERIT' is defined to have a value other
 * than `-1', then the symbolic constant `_POSIX_TRACE' shall also be defined
 * to have a value other than `-1'. */
/* Optionally supported: */
#define _POSIX_ADVISORY_INFO
#define _POSIX_CPUTIME
#define _POSIX_FSYNC
#define _POSIX_IPV6
#define _POSIX_MEMLOCK
#define _POSIX_MEMLOCK_RANGE
#define _POSIX_MESSAGE_PASSING
#define _POSIX_MONOTONIC_CLOCK
#define _POSIX_PRIORITIZED_IO
#define _POSIX_PRIORITY_SCHEDULING
#define _POSIX_RAW_SOCKETS
#define _POSIX_SHARED_MEMORY_OBJECTS
#define _POSIX_SPAWN
#define _POSIX_SPORADIC_SERVER
#define _POSIX_SYNCHRONIZED_IO
#define _POSIX_THREAD_ATTR_STACKADDR
#define _POSIX_THREAD_CPUTIME
#define _POSIX_THREAD_ATTR_STACKSIZE
#define _POSIX_THREAD_PRIO_INHERIT
#define _POSIX_THREAD_PRIO_PROTECT
#define _POSIX_THREAD_PRIORITY_SCHEDULING
#define _POSIX_THREAD_PROCESS_SHARED
#define _POSIX_THREAD_SPORADIC_SERVER
#define _POSIX_TRACE
#define _POSIX_TRACE_EVENT_FILTER
#define _POSIX_TRACE_INHERIT
#define _POSIX_TRACE_LOG
#define _POSIX_TYPED_MEMORY_OBJECTS
#define _XOPEN_CRYPT
#define _XOPEN_REALTIME
#define _XOPEN_REALTIME_THREADS
#define _XOPEN_STREAMS
#define _XOPEN_UNIX
